# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Crank < Formula
  desc "lets you quickly switch between multiple git user profiles"
  homepage "https://github.com/gesquive/git-user"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/gesquive/crank/releases/download/v1.0.0/crank_v1.0.0_darwin_arm64.tar.gz"
      sha256 "41d40f81ace6be5db3990ee7052515077ee68da51b6a1b9b56a4ea6fa26f33ee"

      def install
        bin.install "git-user"
        man.mkpath
        man1.install "docs/manpages/git-user.1", "docs/manpages/git-user-add.1", "docs/manpages/git-user-del.1", "docs/manpages/git-user-edit.1", "docs/manpages/git-user-list.1", "docs/manpages/git-user-rm.1", "docs/manpages/git-user-set.1"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gesquive/crank/releases/download/v1.0.0/crank_v1.0.0_darwin_x86_64.tar.gz"
      sha256 "966e28d4c6b8658fea0c4c65a65b4d02a6f090d17838ae5a36fc62c50e0f45dd"

      def install
        bin.install "git-user"
        man.mkpath
        man1.install "docs/manpages/git-user.1", "docs/manpages/git-user-add.1", "docs/manpages/git-user-del.1", "docs/manpages/git-user-edit.1", "docs/manpages/git-user-list.1", "docs/manpages/git-user-rm.1", "docs/manpages/git-user-set.1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/gesquive/crank/releases/download/v1.0.0/crank_v1.0.0_linux_armv6.tar.gz"
      sha256 "937010a43b56267f74dd9862ec57a9c46e2809483f464157274ba107085147cc"

      def install
        bin.install "git-user"
        man.mkpath
        man1.install "docs/manpages/git-user.1", "docs/manpages/git-user-add.1", "docs/manpages/git-user-del.1", "docs/manpages/git-user-edit.1", "docs/manpages/git-user-list.1", "docs/manpages/git-user-rm.1", "docs/manpages/git-user-set.1"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gesquive/crank/releases/download/v1.0.0/crank_v1.0.0_linux_arm64.tar.gz"
      sha256 "b864abff5c3f6e7a64b1a04fe799e5ae560435c698f68b4e2e74e7e37fe1f6f6"

      def install
        bin.install "git-user"
        man.mkpath
        man1.install "docs/manpages/git-user.1", "docs/manpages/git-user-add.1", "docs/manpages/git-user-del.1", "docs/manpages/git-user-edit.1", "docs/manpages/git-user-list.1", "docs/manpages/git-user-rm.1", "docs/manpages/git-user-set.1"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gesquive/crank/releases/download/v1.0.0/crank_v1.0.0_linux_x86_64.tar.gz"
      sha256 "f9deafdaa229938a8b608ba86bc7a2107a80d414adf17f3ed42fa8a90b9bcada"

      def install
        bin.install "git-user"
        man.mkpath
        man1.install "docs/manpages/git-user.1", "docs/manpages/git-user-add.1", "docs/manpages/git-user-del.1", "docs/manpages/git-user-edit.1", "docs/manpages/git-user-list.1", "docs/manpages/git-user-rm.1", "docs/manpages/git-user-set.1"
      end
    end
  end

  depends_on "git"
end
