# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Crank < Formula
  desc "generate random passwords"
  homepage "https://github.com/gesquive/crank"
  version "1.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/gesquive/crank/releases/download/v1.0.1/crank_v1.0.1_darwin_arm64.tar.gz"
      sha256 "39b167c4d0353b556588097e47ebacb892c52db648e4f76acafa212863eef00d"

      def install
        bin.install "crank"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gesquive/crank/releases/download/v1.0.1/crank_v1.0.1_darwin_x86_64.tar.gz"
      sha256 "3e0c97deb03ee361824e3bc12f3d3691f88af44e8f8f0913cea6435792019571"

      def install
        bin.install "crank"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/gesquive/crank/releases/download/v1.0.1/crank_v1.0.1_linux_armv6.tar.gz"
      sha256 "2c3a108c5bbc372b9c6961e1d964cb45b063efebc483f0eec2487b2bcea3fb31"

      def install
        bin.install "crank"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gesquive/crank/releases/download/v1.0.1/crank_v1.0.1_linux_arm64.tar.gz"
      sha256 "d0e6a75b2861feba81c3e94c434cce5fe6dd2b1877dd98ddc96b33cba069ab53"

      def install
        bin.install "crank"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gesquive/crank/releases/download/v1.0.1/crank_v1.0.1_linux_x86_64.tar.gz"
      sha256 "48dd42a0281627546125735707c396cafa142df55d9415981b01321c5ed93831"

      def install
        bin.install "crank"
      end
    end
  end
end
