# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitUser < Formula
  desc "lets you quickly switch between multiple git user profiles"
  homepage "https://github.com/gesquive/git-user"
  version "2.0.6"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/gesquive/git-user/releases/download/v2.0.6/git-user_v2.0.6_darwin_arm64.tar.gz"
      sha256 "5c6f07abcea5ac9da94869760ff8e91557dcfca6636fae8e5826303b6a0ba7d1"

      def install
        bin.install "git-user"
        man.mkpath
        man1.install "docs/manpages/git-user.1", "docs/manpages/git-user-add.1", "docs/manpages/git-user-del.1", "docs/manpages/git-user-edit.1", "docs/manpages/git-user-list.1", "docs/manpages/git-user-rm.1", "docs/manpages/git-user-set.1"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gesquive/git-user/releases/download/v2.0.6/git-user_v2.0.6_darwin_x86_64.tar.gz"
      sha256 "b59f4faaf9c8d1251dcc4b0674381758c98eeb70551eb6858e7f18fa267d563c"

      def install
        bin.install "git-user"
        man.mkpath
        man1.install "docs/manpages/git-user.1", "docs/manpages/git-user-add.1", "docs/manpages/git-user-del.1", "docs/manpages/git-user-edit.1", "docs/manpages/git-user-list.1", "docs/manpages/git-user-rm.1", "docs/manpages/git-user-set.1"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/gesquive/git-user/releases/download/v2.0.6/git-user_v2.0.6_linux_armv6.tar.gz"
      sha256 "8b1d1b589839b173a631ae280c46f314851e9aa2b846074ced5599e85931cf33"

      def install
        bin.install "git-user"
        man.mkpath
        man1.install "docs/manpages/git-user.1", "docs/manpages/git-user-add.1", "docs/manpages/git-user-del.1", "docs/manpages/git-user-edit.1", "docs/manpages/git-user-list.1", "docs/manpages/git-user-rm.1", "docs/manpages/git-user-set.1"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gesquive/git-user/releases/download/v2.0.6/git-user_v2.0.6_linux_arm64.tar.gz"
      sha256 "6a8e4e0521962a8ad2cab6a0abdc5d3aa98a56b383c48f20404270415fa8b3e5"

      def install
        bin.install "git-user"
        man.mkpath
        man1.install "docs/manpages/git-user.1", "docs/manpages/git-user-add.1", "docs/manpages/git-user-del.1", "docs/manpages/git-user-edit.1", "docs/manpages/git-user-list.1", "docs/manpages/git-user-rm.1", "docs/manpages/git-user-set.1"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gesquive/git-user/releases/download/v2.0.6/git-user_v2.0.6_linux_x86_64.tar.gz"
      sha256 "0377a3491de9f41c0774608a9ff5f1d15eb5e5366cab47665f05abef50af2ecf"

      def install
        bin.install "git-user"
        man.mkpath
        man1.install "docs/manpages/git-user.1", "docs/manpages/git-user-add.1", "docs/manpages/git-user-del.1", "docs/manpages/git-user-edit.1", "docs/manpages/git-user-list.1", "docs/manpages/git-user-rm.1", "docs/manpages/git-user-set.1"
      end
    end
  end

  depends_on "git"
end
