# This file was generated by GoReleaser. DO NOT EDIT.
class Krypt < Formula
  desc "A command line file encrypter and decrypter"
  homepage "https://github.com/gesquive/krypt"
  version "1.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/gesquive/krypt/releases/download/v1.0.0/krypt_v1.0.0_darwin_x86_64.tar.gz"
    sha256 "9b6ec6d56a40354492c2fbe230a0b8aa84d2ce7fa05be07c8cfe46657ecaa770"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/gesquive/krypt/releases/download/v1.0.0/krypt_v1.0.0_linux_x86_64.tar.gz"
      sha256 "0fe54b7fb8d9867677d7d0811f308006a17e2bce0dd2eb813f13c4e542cc93ef"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gesquive/krypt/releases/download/v1.0.0/krypt_v1.0.0_linux_arm64.tar.gz"
        sha256 "eff0209211677ede3847f99eadea9ab1369f92e9dbff294ff17c95cacd10da27"
      else
        url "https://github.com/gesquive/krypt/releases/download/v1.0.0/krypt_v1.0.0_linux_armv6.tar.gz"
        sha256 "911fe9a39c0d7b91dfd7de15ea394f1b4b6e178fb11c82387a762ca438a32a4c"
      end
    end
  end

  def install
    bin.install "krypt"
    man.mkpath
    man1.install "manpages/krypt.1", "manpages/krypt-create.1", "manpages/krypt-edit.1", "manpages/krypt-list.1", "manpages/krypt-reseal.1", "manpages/krypt-seal.1", "manpages/krypt-unseal.1", "manpages/krypt-view.1"
  end
end
