# This file was generated by GoReleaser. DO NOT EDIT.
class Krypt < Formula
  desc "A command line file encrypter and decrypter"
  homepage "https://github.com/gesquive/krypt"
  version "1.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/gesquive/krypt/releases/download/v1.0.1/krypt_v1.0.1_darwin_x86_64.tar.gz"
    sha256 "cf5387e95b1178bda4f8c81c96f72181b174716d5c134773b1ae2fdb3dae928c"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/gesquive/krypt/releases/download/v1.0.1/krypt_v1.0.1_linux_x86_64.tar.gz"
      sha256 "2ec9be82a10fe33118c7d22a82a86c45d82ffb45cc3bba69d06d3ec8644569e6"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gesquive/krypt/releases/download/v1.0.1/krypt_v1.0.1_linux_arm64.tar.gz"
        sha256 "a627ba3a210c46962b7a4ef86ccbc3e2916a4d4176ed30d4b9775b2102af4a19"
      else
        url "https://github.com/gesquive/krypt/releases/download/v1.0.1/krypt_v1.0.1_linux_armv6.tar.gz"
        sha256 "cc143a17077566ae3d791a0ba6521cd9ab3b986a5288d43a7d380cefe9a61ed6"
      end
    end
  end

  def install
    bin.install "krypt"
    man.mkpath
    man1.install "manpages/krypt.1", "manpages/krypt-create.1", "manpages/krypt-edit.1", "manpages/krypt-list.1", "manpages/krypt-reseal.1", "manpages/krypt-seal.1", "manpages/krypt-unseal.1", "manpages/krypt-view.1"
  end
end
