# This file was generated by GoReleaser. DO NOT EDIT.
class Krypt < Formula
  desc "A command line file encrypter and decrypter"
  homepage "https://github.com/gesquive/krypt"
  version "1.1.0"

  if OS.mac?
    url "https://github.com/gesquive/krypt/releases/download/v1.1.0/krypt_v1.1.0_darwin_x86_64.tar.gz"
    sha256 "d92a2560831695888fe49dcf06fd07f6313ba5735395ef6eda6c2c5b8e07be87"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/gesquive/krypt/releases/download/v1.1.0/krypt_v1.1.0_linux_x86_64.tar.gz"
      sha256 "e6b033a30802e60e0dfdebee199d095b31a4c691e815b6b37ef444facc33bdcf"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gesquive/krypt/releases/download/v1.1.0/krypt_v1.1.0_linux_arm64.tar.gz"
        sha256 "a6e0662f3d6738bb841e8d37ad963b14ce558bb7a744f6308b9761713fbc8b86"
      else
        url "https://github.com/gesquive/krypt/releases/download/v1.1.0/krypt_v1.1.0_linux_armv6.tar.gz"
        sha256 "d8a344c74b8d8f920ee5501fe613a73dd330480fbc0687ac9624273831fb1c32"
      end
    end
  end

  def install
    bin.install "krypt"
    man.mkpath
    man1.install "manpages/krypt.1", "manpages/krypt-create.1", "manpages/krypt-edit.1", "manpages/krypt-list.1", "manpages/krypt-reseal.1", "manpages/krypt-seal.1", "manpages/krypt-unseal.1", "manpages/krypt-view.1"
  end
end
