# This file was generated by GoReleaser. DO NOT EDIT.
class Rip < Formula
  desc "Sends a text file line by line to a remote host/port"
  homepage "https://github.com/gesquive/rip"
  version "0.2.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/gesquive/rip/releases/download/v0.2.2/rip_v0.2.2_darwin_x86_64.tar.gz"
    sha256 "19776437a54e0df8ceb5b7ed8fa8aa6552e12d632d2acec84ddd2599e090a9e0"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/gesquive/rip/releases/download/v0.2.2/rip_v0.2.2_linux_x86_64.tar.gz"
      sha256 "5a0700312b5e064a14e2cb342ab276e504ae8b01c66a3f50d731d838387521f0"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gesquive/rip/releases/download/v0.2.2/rip_v0.2.2_linux_arm64.tar.gz"
        sha256 "fe6fd147666b47397a1e3ecf34be94b656ac9c17eb3226befd5997ddbb9e742c"
      else
        url "https://github.com/gesquive/rip/releases/download/v0.2.2/rip_v0.2.2_linux_armv6.tar.gz"
        sha256 "7978000a10c6f535cf070cc69b3dde31c7269e7fae9970384b0c6f9f7bb44e47"
      end
    end
  end

  def install
    bin.install "rip"
  end
end
